### ISSUE TITLE
Testear ejemplo y evaluar dificultad

### ISSUE THREAD

**Issue by lronaldo** [AssemblerClub/z80asmmooc#1]
Ejemplo de programación nivel inicial: https://github.com/AssemblerClub/z80asmmooc/blob/master/examples/pixel_rojo.asm
- Probad a realizar el ejemplo
- Comentar sobre la dificultad estimada para personas con 0 conocimientos de ensamblador.

Toda contribución es más que bienvenida :smile: 

Una vez el ejemplo esté visto, crearemos una versión en vídeo de los contenidos a modo de prueba.

@aalmiramolla @Blitzman @Davitsu @eduardobs79 @peterAmoros @heclinares @realmml @AugustoRuiz

**Comment by fmgb** [comment]
Hola,
He realizado el ejemplo y he de comentar los siguientes puntos:
- 10001000b no es 132d, sino 136d
- En el ejercicio 3, u otro ejercicio, pintar los 4 píxeles con las combinaciones siguientes: 10, 01,00,11, por ejemplo.
- Respecto a los Retos Creativos, creo que son bastante avanzados para personas que tenga 0 conocimientos de programación, al menos que hagas un nuevo apartado, no teórico, sino algo como: 
  NOTA: Para la realización de estos ejercicios tienes la posibilidad de utilizar 'esto, esto y lo otro'.

Nivel de dificultad para un persona con 0 conocimientos: Aceptable.

Nivel de documentación teórica: Muy bueno. Posiblemente añadiría los prefijos para nombrar a direcciónes de memoría '&', utilización de binarios '%', '#' número, etc.

Sin más,
Un saludo y a seguir trabajando :+1: 
Francisco Manuel García Botella
