### ISSUE TITLE
Video 0.2: Estructura del curso

### ISSUE THREAD

**Issue by lronaldo** [AssemblerClub/z80asmmooc#10]
@AssemblerClub/the-order-of-the-z80 

Contínuo con las pruebas. Ahora el vídeo explicando la [**estructura del curso**](https://youtu.be/lGMDyK49m8A)

[![0.2 Estructura](https://img.youtube.com/vi/dzXi23oM5aE/mqdefault.jpg "0.2 Estructura")](https://youtu.be/dzXi23oM5aE) 

Si alguien quiere colaborar en mejorar los assets del video, se agradecería mucho :).

¿Opiniones?

**Comment by Gaspar1992** [comment]
Me gustaría saber si también en un momento avanzado del curso podrías enseñar Hacks que tenga la maquina o trucos utilizados por otros desarrolladores en Amstrad para sacarle mayor rendimiento o mayor funcionalidad. Por el resto me parece bien los planteamientos del curso, así será más vistoso los trabajos y ejercicios, viendo nuestros frutos nos motivará más.

**Comment by lronaldo** [comment]
@Gaspar1992 Sí, habrá mucho detalle de funcionamiento interno a lo largo del curso, y muchas técnicas y hacks. Evidentemente, será en niveles más avanzados, pero sí, la idea es profundizar. 

De hecho, hacia el final del curso incluso me gustaría incluir otras arquitecturas (MSX, Spectrum, etc) para poder ver diferencias y poder incluso trabajar en multiplataforma para varios Z80. De todas formas, esto último está aún en proceso.

**Comment by lronaldo** [comment]
@AssemblerClub/the-order-of-the-z80 

¿Podríais comparar el audio de este vídeo y [**del anterior**](https://youtu.be/lGMDyK49m8A)?

El volumen en este segundo está más alto y tiene otro postprocesado. Me interesa saber,
1. Si preferís este posprocesado
2. Si el volumen es suficiente o hace falta más.

Gracias, chicos :)

**Comment by AugustoRuiz** [comment]
Yo prefiero este postprocesado, y el volumen está muy bien.

**Comment by DSkywalk** [comment]
Perfecto, sin ninguna duda este postprocesado es muchísimo mejor, excelente :+1:

**Comment by eldeljar** [comment]
Mucho mejor la segunda versión.

En cuanto al volumen, personalmente prefiero que se suba un poco más.

**Comment by Phantomas2** [comment]
El audio del video está muy bién. La estructuración que has introducido se entiende perfectamente.

**Comment by heclinares** [comment]
Ya lo han comentado, pero es cierto que el volumen del primer vídeo está
demasiado bajo, el del segundo ok.

En cuanto al tema de assets, para empezar, yo haría un buen repaso de
tipografías. Me da la sensación que has elegido colores relacionados con el
CPC (ese amarillo y ese azul delatores), así que una fuente que tenga el
toque pixel, pero sin dificultar la lectura, al menos para el título,
podría ser una buena opción.

*Edit*
He hecho una prueba y el toque pixel para el título... no me acaba de
convencer. Paso la captura con una prueba alienando a la izquierda en lugar
de centrado, título con efecto pixel y un pequeño ribete de detalle para el
cuadro de la derecha.

​

**Comment by lronaldo** [comment]
@heclinares Ten en cuenta que estás respondiendo a un issue de Github. Si respondes por correo, el adjunto se pierde. La captura no aparece.

Los colores, en principio, no eran por el CPC en particular, aunque dada la elección, podrían haberlo sido. He elegido colores simples y claros para buscar sencillez y legibilidad. El mismo motivo para la fuente. No buscaba tematizar, sino simplificar y mejorar la legibilidad lo más posible. 

El título tiene alineación izquierda para diferenciarlo, es un poco más grande y en amarillo. El texto está centrado porque vi que quedaba mejor que en alineación derecha. Busco con eso diferenciación del título también. Los textos son más pequeños que el título.

La tipografía es Arial, que creo que queda bastante suave y tiene buena legibilidad para textos telegráficos como estos.

Todo eso es la idea que hay detrás del montaje. Por otra parte, me gusta siempre reducir la cantidad de texto al mínimo indispensable e incluir imágenes allá donde sea posible. Creo que es aún bastante mejorable en este sentido. Lo que pasa es que no me gustan las imágenes "evocadoras". Prefiero las imágenes específicas de lo que se está tratando o ejemplos concretos. No veo valor en metaforizar textos con imágenes evocadoras en general. En mi opinión, provocan diversificación mental y pueden desconcentrar e incluso generar ideas equivocadas.

A partir de esto, todas las sugerencias son más que bienvenidas 👍 😄

**Comment by heclinares** [comment]
Ok, me temía lo del email...
La captura no merece mucho la pena, pero igualmente la cuelgo para que puedas tener otra referencia:
![fran_test1](https://cloud.githubusercontent.com/assets/8360457/24700073/57b48656-19f6-11e7-8b8d-8a3a9344817d.png)

**Comment by Raymost** [comment]
Sobre ambos vídeos. Me gusta el contraste que tienes con la pared. Lo que
no me gusta es tu suéter, una camisa te da mejor rollo. 😝
Efectivamente hay que mejorar esos assets. Tambien creo que estando mas
centrado ganarías en presencia y comunicación. Así como hacer unas cuantas
cosas mas con la imagen. Vamos que, ¿cuando quedamos para ver todo eso? 😆

2017-04-03 21:45 GMT+02:00 Francisco Gallego <notifications@github.com>:
