### ISSUE TITLE
Video 1.P3: Ejemplo Práctico de Solución del Reto 1.1

### ISSUE THREAD

**Issue by lronaldo** [AssemblerClub/z80asmmooc#11]
@AssemblerClub/the-order-of-the-z80 

Por fin he podido volver a la carga con la grabación de vídeos. Aquí tenéis el **[primer vídeo práctico](https://youtu.be/NxI2kBarAhw)** que he grabado con un formato que espero ya sea definitivo, gracias a la colaboración de Raúl Ortega Palacios (ex grafista de Dinamic).

[![1.P3 Ejemplo Práctico Reto 1.1](https://img.youtube.com/vi/NxI2kBarAhw/mqdefault.jpg "1.P3 Ejemplo Práctico Reto 1.1")](https://youtu.be/NxI2kBarAhw) 

Decidme qué os parece el **_nuevo montaje, la calidad del audio y el contenido_**.

Personalmente, creo que aún tengo que reducir los vídeos a entre 5 y 8 minutos. Este se me ha ido a 12.

**Comment by Raymost** [comment]
Me gusta mucho como ha quedado. ¿Has pensado en grabar tus explicaciones y
lo que se muestra por separado? En todo caso creo que queda muy claro
todo. 😆

**Comment by lronaldo** [comment]
Me alegro que te guste, @Raymost. Si te refieres a grabar el audio y el vídeo por separado, lo hago así en los vídeos de teoría. Los de prácticas, como este, el montaje es en OBS, por lo que sale un único archivo, aunque lleva el audio y el vídeo en canales separados. De todas formas, creo que no es eso a lo que te refieres, no?

**Comment by Raymost** [comment]
Exacto. No me refería a ello. Si no al vídeo de ti explicando el tema y por
otro lado la infografia. Como lo haces ahora se que es mucho mas rápido,
pero de la otra manera puede quedar mejor.
En todo caso es cuestión de opinión. Ya que tampoco tengo nada para
mostrarte mi idea. 😅

**Comment by eldeljar** [comment]
Para mis escasos conocimientos, las explicaciones son muy claras y se entienden fácilmente. El video no me ha parecido tan largo, teniendo en cuenta que es un video de introducción. 

El sonido también me ha parecido correcto.

Muchas gracias por el esfuerzo de hacer estos videos.

**Comment by lronaldo** [comment]
@eldeljar Muchas gracias a ti por darme feedback. Es muy importante, sobre todo viniendo de quienes tenéis menos conocimiento, ya que el curso debe ser para vosotros. Me interesa mucho cualquier duda que te genere cualquiera de los vídeos. Cuanto más feedback, mejor puedo hacer el curso.

Mil gracias 😄

**Comment by Hark0** [comment]
Audio y video correctos. El asunto de hacer zoom en las zonas de pantalla en las que trabajas me parece imprescindible; se distinguen los datos perfectamente. 

Como titulo a lis videos yo diferenciaría con una palabra inicial "el tipo de contenido", por ejemplo:

1.P3 - TEORIA: Ejemplo práctico.

y cuando sea un reto:

1.P3 - RETO: Ejemplo práctico.

De esta forma será más fácil encontrar el vídeo en cuestión cuando el curso tenga muchos más videos.

La duración de 10~15 min. me parece de lo más acertada.

**Comment by lronaldo** [comment]
Me parece muy adecuado añadir las palabras clave a los vídeos. Buen consejo 👍 

Siempre que grabo los vídeos me centro en que duren lo menos posible, pero no consigo reducir los 12 minutos más o menos con estos prácticos. De momento todos coincidís en que es una buena duración, lo que me tranquiliza un poco. Aun así, creo que es bueno que me esfuerce en reducir al mínimo el tiempo necesario para cada cosa, y procure no pasar de los 12-15 minutos.

Gracias 😄
