### ISSUE TITLE
Vídeo 1.P4. Jugando Con el Código

### ISSUE THREAD

**Issue by lronaldo** [AssemblerClub/z80asmmooc#12]
@AssemblerClub/the-order-of-the-z80 

Continuando con los vídeos prácticos, este es una explicación para iniciados sobre cómo **[aprender practicando, cambiado cosas en el código](https://youtu.be/bdkhjQDioHY)**.

[![1.P4 Jugando con el Código](https://img.youtube.com/vi/bdkhjQDioHY/mqdefault.jpg "1.P4 Jugando con el Código")](https://youtu.be/bdkhjQDioHY) 

El montaje es idéntico al anterior, en la línea práctica. He añadido este contenido porque creo que es esencial para aquellos que aprendan programación desde 0 con este curso. **_¿Qué opináis?_** 

Nuevamente, el vídeo se me ha ido a 10 minutos. Quizá puedo reducirlo quitando la explicación sobre el aprendizaje práctico, que debería estar en la línea de vídeos prácticos.

Planeo añadir otro vídeo igual con la explicación sobre cómo ejecutar los programas paso a paso y cómo añadir más instrucciones al programa, replicando patrones conocidos.

**Comment by ronsonmaria** [comment]
Buenos días,

En primer lugar darte la enhorabuena por los vídeos, no hay manera mejor de desayunar que con él colacao y el ensamblador jeje! Ahora al lío:

- dicción: perfecta , como siempre.
- contenido: perfecto, primero práctica y luego entender lo que has hecho ( teoría )
- diseño marco:  correcto, me parece bien poner la pantalla dentro de un amstrad.
- posición tuya en los vídeos : ahí es donde no estoy de acuerdo. Mi cerebro tiende a ver de izquierda a derecha , y pasó más tiempo viendo tu cara que el código, me cuesta más seguir el código porque tengo que "obligarlo" a mirar a la izquierda. Para mí sería perfecto que estuvieras a la derecha , arriba o abajo, pero a la derecha.

Por lo demás perfecto, vamos a practicar ! Muchas gracias por todo fran.

Saludos 

Enviado desde mi Spectrum +128 de Amstrad

**Comment by lronaldo** [comment]
Muchas gracias por la review @ronsonmaria. 

La posición a la izquierda la elegí precisamente para poder dar más peso a la presencia del profesor en los vídeos. Estuve pensando sobre ello en su día, y la posición derecha resultaba más fría en general. Sí es cierto que eso me da más protagonismo, en lugar de dárselo a la zona de explicación, pero pensé en su momento que merecía la pena que el seguimiento de la explicación fuera guiado por los gestos del profesor. 

De todas formas, sí me gustaría contar con más opiniones al respecto. No descarto la posibilidad de cambiarlo, pero sí me gustaría tener una buena muestra de percepciones al respecto, ya que inicialmente las opiniones eran más favorables al lado izquierdo.

@AssemblerClub/the-order-of-the-z80 **_¿Preferís profesor al lado izquierdo o al lado derecho?_**

**Comment by eldeljar** [comment]
Muy interesante el vídeo. Me gusta más este enfoque más practico.

Como siempre las explicaciones muy claras, y el sonido bien. 

En cuanto a la ubicación del profesor, en mi caso me es indiferente y no tengo ninguna preferencia.

Muchas gracias por el esfuerzo de hacer estos videos.

**Comment by lronaldo** [comment]
Genial, @eldeljar. A ver si me da tiempo y puedo grabar pronto los vídeos con los retos de este nivel para que podáis hacerlos y darme feedback respecto a la dificultad de los mismos. Espero que después de los vídeos prácticos os sea más fácil afrontar los retos.

Como siempre, mil gracias a vosotros por el feedback. 😄
