### ISSUE TITLE
Vídeo 1.P5. Ejecutando Paso a Paso

### ISSUE THREAD

**Issue by lronaldo** [AssemblerClub/z80asmmooc#13]
@AssemblerClub/the-order-of-the-z80 

Tercer vídeo práctico y probablemente último de los importantes del nivel 1. En este se muestra cómo **[ejecutar paso a paso y añadir nuevas instrucciones al programa](https://youtu.be/sLNwD2LPEOA)**.

[![1.P5 Ejecución Paso a Paso](https://img.youtube.com/vi/sLNwD2LPEOA/mqdefault.jpg "1.P5 Ejecución Paso a Paso")](https://youtu.be/sLNwD2LPEOA) 

Nuevamente, los vídeos se me alargan más de lo planeado. **_¿Creéis que merecería la pena partir algunas explicaciones en 2?_**

**Comment by eldeljar** [comment]
Muy buen video. Imagen y sonido correctos, y a mi gusto, el tiempo del video también está bien. 

La explicación de cómo depurar es muy instructiva, sobre todo para personas que no hayan depurado nunca programas en ensamblador. La idea de poner un error para ilustrar la explicación es muy acertada, sobre todo porque lo de sobrescribir un registro por error nos pasará a menudo a lo largo del curso.

En cuanto a la pregunta, si te refieres a partir este video en 2, personalmente me gusta como ha quedado y por tanto no lo partiría.

Saludos y muchas gracias

**Comment by Gaspar1992** [comment]
Muy buen vídeo, a mi parecer no me parece larga la duración, podría comprender la división de un vídeo de duración igual o mayor a 20 minutos. No creo que sea necesaria una partición.

Saludos y esperare los siguientes con ansias

**Comment by lronaldo** [comment]
@eldeljar @Gaspar1992 Me alegro de que los tiempos de los vídeos os parezcan bien. Personalmente sigo teniendo la sensación de que alargo demasiado las explicaciones, pero me alegra ver que vuestro feedback es positivo. En cualquier caso, intentaré que ninguna explicación se extienda más de la longitud de estos vídeos.

Sobre todo, si en cualquier momento os surgen dudas o hay cosas que no entendáis, que no podáis seguir... Todo ese tipo de detalles me interesan mucho. Aunque, claro está, todo eso tendréis que empezar a verlo conforme resolváis los retos aplicando lo aprendido.

Gracias por el feedback. Espero poder seguir a buen ritmo, que el tiempo apremia. El curso tiene que estar listo al empezar septiembre :smile:.
