### ISSUE TITLE
Videos 1.P2: Instalación de WinAPE en Windows, Linux y Mac OSX

### ISSUE THREAD

**Issue by lronaldo** [AssemblerClub/z80asmmooc#14]
@AssemblerClub/the-order-of-the-z80 

El segundo vídeo práctico del nivel 1 es la instalación de WinAPE, el emulador de Amstrad CPC. He preparado 3 vídeos distintos, uno para cada sistema operativo. Aquí tenéis los 3: 

[![1.P2.W. Instalar WinAPE en Windows](https://img.youtube.com/vi/YIrbPEinYp0/mqdefault.jpg "1.P2.W. Instalar WinAPE en Windows")](https://youtu.be/YIrbPEinYp0) 

[![1.P2.M. Instalar WinAPE en Mac OSX Sierra](https://img.youtube.com/vi/4a_dh0WXWic/mqdefault.jpg "1.P2.M. Instalar WinAPE en Mac OSX Sierra")](https://youtu.be/4a_dh0WXWic) 

[![1.P2.L. Instalar WinAPE en Linux](https://img.youtube.com/vi/aItoD7OfdkM/mqdefault.jpg "1.P2.L. Instalar WinAPE en Linux")](https://youtu.be/aItoD7OfdkM) 

Son videos muy completos, paso a paso, para que la instalación resulte fácil. Si no tenéis WinAPE instalado, sería interesante que lo siguierais para vuestro SO favorito y comprobaseis que funciona.

Como siempre, todo feedback es más que bienvenido :)

**Comment by Hark0** [comment]
Un pequeño comentario, lo he descargado y ejecutado en la máquina del trabajo que es bastante nueva - tiene apenas 2 meses- (Windows 64).

A la hora de ejecutarlo _puede pedir_ (como es mi caso), la instalación de DirectPlay.

Aunque Windows 10 puede instalarlo automáticamente yo he obviado este paso... y **el emulador funciona perfectamente**.

;-)

![directplay_winape](https://user-images.githubusercontent.com/7446823/27136442-9cf1673c-511b-11e7-91d9-a831039b86a0.png)

**Comment by lronaldo** [comment]
Sí, es cierto que en Windows 10 pide DirectPlay. Iba a grabar este vídeo en Windows 10, pero en la máquina virtual el emulador no era capaz de renderizar por algún motivo que desconozco. Por eso decidí hacerlo en Windows 7, y también porque las diferencias son mínimas, como esta, y no muy relevantes. Quizá puedo añadir una nota para usuarios de Windows 10. Será útil :).

**Comment by AugustoRuiz** [comment]
Hola Fran,

Yo tengo un Windows 10 con WinAPE (y la cpctelera, of course), ¿qué
necesitaría para poder grabar una parte con Windows 10? Si interesa, cuenta
con ello :)

Saludos,

2017-06-14 23:07 GMT+02:00 Francisco Gallego <notifications@github.com>:

**Comment by Reyeselda95** [comment]
Hola Fran, 
Yo he probado antes el emulador con Windows 10 y me emulaba las cosas bien. Si bien decir que a veces fallaba (sobre todo el audio) debido a que la configuración por defecto de WinApe debía cambiarse a una que el sistema aceptara. Si lo estabas grabando en una máquina virtual de Windows 10 puede que sea tu problema, porque el sistema necesita más RAM y no puede dedicar dicha RAM a renderizar. Si puedes configurar tu emulador (VirtualBox, vmware, etc.) para que le dé más RAM al sistema invitado deberías poder renderizar sin problemas.

**Comment by lronaldo** [comment]
@AugustoRuiz Gracias :). Puedes grabar un vídeo si quieres. Sólo necesitarías OBS, un buen micrófono, un espacio sin ruidos y un poco de paciencia para grabar un vídeo similar al de Windows 7. Yo te podía pasar los assets y la configuración del OBS.

 @Reyeselda95 Lo probaré, pero dudo que el problema sea la RAM. La máquina virtual de Windows 10 la tengo configurada con 6 GB de RAM, cosa que debería ser más que suficiente para el sistema operativo y el WinAPE. De hecho, no consume los 6GB completos, por lo que dudo que ese sea el problema. De todas formas, lo probaré por si acaso. Gracias por el consejo :).

**Comment by AugustoRuiz** [comment]
Estaba pensando en hacer solo el video, y que la voz fuese en off. Sería un
poco raro tener un vídeo con un audio y otros con otro...

2017-06-15 14:30 GMT+02:00 Francisco Gallego <notifications@github.com>:
