### ISSUE TITLE
Videos 1.P6 y 1.P8: RETOS 1 y 2

### ISSUE THREAD

**Issue by lronaldo** [AssemblerClub/z80asmmooc#15]
@AssemblerClub/the-order-of-the-z80 

Primeros dos vídeos de presentación de los retos a realizar para superar el nivel 1. 

- **[RETO 1: Utiliza los colores](https://youtu.be/Uzqsd0gurO8)**
[![1.P6 RETO: Utiliza los colores](https://img.youtube.com/vi/Uzqsd0gurO8/mqdefault.jpg "1.P6 RETO: Utiliza los colores")](https://youtu.be/Uzqsd0gurO8) 
- **[RETO 2: Domina el formato](https://youtu.be/xot6JFIwHtM)**
[![1.P8 RETO: Domina el formato](https://img.youtube.com/vi/xot6JFIwHtM/mqdefault.jpg "1.P8 RETO: Domina el formato")](https://youtu.be/xot6JFIwHtM) 

Esta es la parte más importante del curso. Los retos debe ser posible y divertido hacerlos. 

Aquí es donde más colaboración necesito por vuestra parte:
- **¿Cuánto tiempo os cuesta resolver las actividades y los retos?**
- **¿Podéis resolverlos? ¿Resulta muy difícil?**
- **¿Resultan entrentenidos, amenos, útiles?**

**Comment by Hark0** [comment]
Reto 1 terminado, la única dificultad creo era averiguar como funciona (formato) de "1 byte" de pantalla. He tenido que buscar la información técnica sobre el vídeo del CPC. (Si hay vídeos teóricos con esta información, _postea_ el link, ya que no he sido capaz de encontrarlo). 

;-)

**Comment by Hark0** [comment]
Reto 2... o bien hago un programa largo de narices... o bien utilizo otras instrucciones como dices en el video... pero vuelvo a lo de antes ¿donde has explicado las instrucciones E3 y 21? ¿nos toca a nosotros investigar su funcionamiento?

**Comment by lronaldo** [comment]
@Hark0 Genial 😄 

El vídeo explicativo del formato del byte de pantalla estará, pero aún no está. Será un vídeo de la línea de vídeos de teoría. De momento, estoy concentrado en terminar la línea principal hasta el nivel 1, que es la línea de vídeos de práctica. Después haré los de teoría y aprendizaje.

**Comment by Hark0** [comment]
Ok! De momento realizado "sin bonus"... aunque ya estaba yendo a mi biblioteca a por el manual del Z80 ;-)

**Comment by lronaldo** [comment]
@Hark0 Si te fijas, el Reto 2 es el vídeo P8. Grabé los dos retos juntos y ayer grabé el vídeo P7, que es justo el que introduce las instrucciones 21 y 22. Ten en cuenta que no siempre voy a grabar los vídeos en orden cronológico, pero sí lo estoy numerando ;). Si en algún momento he dicho algo de la instrucción E3, es un error, porque la instrucción es la 3E, que es LD A, #, la que estáis usando desde el principio.

**Comment by Hark0** [comment]
Me estoy dando cuenta de eso, creo que deberías "etiquetar" de una forma más clara qué tipo de vídeo es. TEORIA / PRACTICA / RETO. Me estoy liando con el orden... XD

**Comment by lronaldo** [comment]
@Hark0 Te estás liando con el órden porque no te has leído las explicaciones de cuál es la orientación del curso. El curso no es estándar, sino guiado por la práctica. Eso significa que los conceptos no tienen porqué explicarse antes de que los apliques, sino que de las dudas que te surjan al aplicar es de donde sacarás el interés por ver los vídeos de teoría. Los vídeos de teoría aún no están hechos, por eso no hay ninguno etiquetado como TEORIA. Estoy terminando la línea práctica primero. 

Échale un ojo al contenido en el repositorio, en particular:
- https://github.com/AssemblerClub/z80asmmooc/blob/master/contents/videos/resumen.txt
- https://github.com/AssemblerClub/z80asmmooc/tree/master/contents/videos
- https://github.com/AssemblerClub/z80asmmooc/blob/master/contents/nivel_01/videos/resumen.txt

Por otra parte, fíjate en que los vídeos están numerados ;)
