### ISSUE TITLE
 Vídeo 1.P9. EJEMPLO: Pintando por la Pantalla

### ISSUE THREAD

**Issue by lronaldo** [AssemblerClub/z80asmmooc#17]
@AssemblerClub/the-order-of-the-z80 

**[Ejemplo de cómo localizar posiciones de la pantalla de forma práctica para pintar píxeles](https://youtu.be/JPabJE_-IGA)**
[![1.P9 EJEMPLO: Pintando por la pantalla](https://img.youtube.com/vi/JPabJE_-IGA/mqdefault.jpg "1.P9 EJEMPLO: Pintando por la pantalla")](https://youtu.be/JPabJE_-IGA) 

Este vídeo sí que se me ha ido un poco de largo más de que los demás. Creo que debería repetirlo y acortarlo. Incluso me parece que se hace un poco pesado. ¿Qué os parece?

**Comment by Hark0** [comment]
Aunque la explicación es muy clara... opino que deberías obviar las explicaciones acerca de "conversiones dec -> hex", creo que basta con decir que todo el rato trabajamos en hexadecimal.

Por otro lado sería ideal que explicaras en un vídeo el formato de pantalla (y sus diferentes modos), aunque es cierto que en éste se explica, hay que "deducirlo". ;-)

**Comment by lronaldo** [comment]
@Hark0 Las conversiones hex->decimal en este caso se me hacen necesarias. Alguien que no ha trabajado en hexadecimal no puede identificar cuál es el tamaño de la pantalla si no se lo indicas primero en decimal. Una vez hecho esto, la conversión es necesaria para ir asociando. De todas formas, al igual que te decía antes, habrán vídeos de teoría sobre decimal y hexadecimal. Aquí sólo se hace un poco de introducción práctica por necesidad.

En cuanto a los modos gráficos, lo mismo que decía. Las explicaciones de los mismos van en los vídeos de teoría. La teoría en este curso es opcional: el que la necesite llegados a estos vídeos, podrá ir a buscarla (para eso está) y así entender y averiguar cómo van formatos y modos. El que no la quiera o necesite, o el que prefiera descubrir por sí mismo, no tiene por qué tragársela. Es el formato del curso: hilo conductor práctico, y teoría como apoyo.
