### ISSUE TITLE
Acerca de aumentar la definición de Winape

### ISSUE THREAD

**Issue by Reyeselda95** [AssemblerClub/z80asmmooc#19]
@lronaldo Me he puesto a intentar hacer algunas cosillas sobre el código del reto 1 y he intentado aumentar la imagen con la lupa (Aviso, en Windows). Mi problema es que me aparecen más colores de los que en un principio queremos manejar (en modo 0).
![conseguido](https://user-images.githubusercontent.com/22152673/27242090-d46a1a30-52db-11e7-98dd-dae2c784de74.PNG)
Esta es la imagen del resultado de una captura en la que, pese a ser pequeña, puede apreciarse un fade entre los colores. ¿Habría alguna manera en la que pudiese mejorar la definicion de los colores para que no se mostrase este fade?

(WinApe lo instalé con CPCtelera y CygWin)

**Comment by lronaldo** [comment]
Pues ciertamente no sabría qué decirte. Lo único que se me ocurre es que no uses la lupa, saques un screenshot y lo amplíes con el GIMP o algo similar. Es menos práctico, pero debe funcionarte bien. Entiendo que la única forma de que la lupa amplíe sin ese difuminado sería que te permita configurarla. Si no, supongo que las alternativas son lo que te digo, o usar otro software de lupa distinto.

**Comment by Reyeselda95** [comment]
Esa imagen en concreto está sacada sin utilizar la lupa, simplemente utilicé la herramienta recortes y luego amplié con Phososhop (estoy mas acostumbrado). La cosa es que creo k la resolucion es cosa de la emulacion, por eso te preguntaba, por si es unicamente cosa mía o es por culpa de windows. Es algo que me extrañaría bastante la verdad, dado que el programa es un .exe ....

**Comment by Reyeselda95** [comment]
OK, ya he encontrado como se arregla. Dentro de las opciones del menú de display, hay que DESMARCAR la opción "PAL emulation" que viene por defecto. De este modo desaparece el fade. 😸 
![meh](https://user-images.githubusercontent.com/22152673/27512514-31ca6e38-5943-11e7-82a8-ba6704a8a863.PNG)

**Comment by lronaldo** [comment]
@Reyeselda95 Pensaba que ya lo tendrías desactivado. En los tutoriales de instalación explico que hay que quitar esa opción para mejorar la nitidez de la imagen :). 

Me alegro que lo hayas encontrado. Eso resuelve el caso 👍
