### ISSUE TITLE
Evaluación vídeo Desafío 1-1

### ISSUE THREAD

**Issue by lronaldo** [AssemblerClub/z80asmmooc#3]
Hola a todos,

Espero que estéis pasando un buen verano :grinning:. 

Os dejo el [**primer vídeo del curso de Ensamblador Z80**](https://www.youtube.com/watch?v=Ng9n24UPJlY). Si tenéis un rato para verlo, agradecería mucho el feedback.

Notas:
- La estructura del curso está concebida como: Curso <-- Niveles <-- Desafíos <-- Retos. (<-- subconjunto de)
- Para cada desafío, se muestran uno o varios retos iniciales como ejemplo.
- Para los demás retos habrán pistas o explicaciones, pero no se muestra su resolución.
- En los vídeos se enlazará a los contenidos teóricos que sean necesarios. La idea es que los alumnos aprendan lo que necesiten para resolver los retos, pero siempre a su ritmo y según sus necesidades. Son siempre los alumnos quienes navegan por los vídeos que les hacen falta o consideran interesantes.
- Habrá una introducción al curso que explique todo esto.
- También habrá una breve introducción a cada nivel, explicando los objetivos.

Feedback especialmente interesante:
- Contenidos teóricos que consideréis oportuno explicar
- Ideas prácticas sobre nuevos retos, desafíos o ejercicios
- Fallos de explicación, correcciones sobre el vídeo
- Ideas de mejora de explicación
- Ideas de mejora estética
- Ideas sobre cómo acortar los vídeos (La duración ideal no debería ser superior a 5 minutos)

Mil gracias por vuestra ayuda :)

@ronsonmaria @Darky-Lucera @Davitsu @dfreniche @aalmiramolla @AmstradGamer @AugustoRuiz @Blitzman @fmgb @Raymost @villagra-abp @eduardobs79 @heclinares @peterAmoros @realmml

**Comment by dfreniche** [comment]
Buenas a todos,

Feedback “malo” 😉:
- creo que el sonido de tu voz mejoraría bastante con un micro unidireccional. Yo uso un Blue Snowball, pero cualquiera (que no sea directamente el de la web cam / ordenador) creo que mejoraría el sonido de la voz. No es que no se entienda, o el volumen no sea el adecuado, es que podría sonar mejor.
- música de fondo: la bajaría incluso más. Pero eso son manías mías.
- cómo contar el hexadecimal: las posiciones de memoria en un ordenador se cuentan en hexadecimal, que tiene 16 símbolos para los números (desde el 0-9 y desde A-F), en lugar de los 10 habituales en decimal (desde el 0-9). Por eso pasar de la posición 0000 - 0010 supone contar hasta 10 en hexadecimal que serían 16 en decimal. Si cuentas las columnas con datos en memoria verás que hay 16 posiciones (01, 89, 7F, etc)
- estética: veo demasiado logo, y el fondo, etc. Entiendo que el logo aparezca en la diapositivas, pero está también en el vídeo y luego los fondos… Entre tu cara, las pantallas, etc lo veo un poco abigarrado. Ojo que no es que no se entienda. Es una cuestión meramente estética.

Feedback “bueno”:
- empezar escribiendo directamente código de máquina (ni siquiera ensamblador) directamente en la memoria (sin un cargador BASIC ni DATAs ni nada) te hace sentirte el PUTO AMO.
- el remarcar las zonas de pantalla, etc. en rojo es un WIN (de los de ganar, no de los de M$) 😈
- empezar haciendo algo práctico es muchísimo mejor que empezar explicando los registros, la arquitectura de la CPU, organización de memoria, etc. Te sientes como un tonto porque no sabes qué estás haciendo, pero es mejor así.

Para ir razonando sobre los valores en Hex que hay que meter para cambiar los colores me he hecho esta hoja de cálculo de “vuelva usted a aprender qué era binario, Hex y decimal”. Por si a alguien le sirve:

https://docs.google.com/spreadsheets/d/10UAkvvQWF5JmSNAT7yG_a1IX6WpDGtTTynvd4hTVIU4/edit?usp=sharing

## 

Diego Freniche Brito
Blog: http://blog.freniche.com
LinkedIn: http://es.linkedin.com/in/dfreniche

**Comment by ghost** [comment]
Buenas.

Acabo de ver el video y coincido con Diego en lo de que a veces hay demasiada información en pantalla o demasiado junta. No sabría qué proponer para mejorarlo, puesto que es muy interesante tenerla toda y se agradecen las zonas ampliadas. También tener la caja con Fran explicando da una sensación de cercanía que creo que es buena. El sonido me parece correcto.

En cuanto al contenido: Para mi está claro, bien y es un buen comienzo, pero en el video se comenta que no importa si no se entiende la traducción del código máquina a ensamblador, que ya lo veremos, pero por otra parte se plantean unos retos que creo que una persona que no entienda en absoluto el código ensamblador del video pueda si quiera plantearse en completar. Además debería ensamblarlo. Veo un "gap" en este punto.

Por otro lado pienso que quien se plantee seguir un curso de ensamblador, por muy básico que sea el inicio, un mínimo de conocimiento se ha de tener, por lo que no sé si es un problema o no.

Para entender "la magia" que ocurre al ejecutar ese código hexadecimal que ponemos se han de dar por supuestas unas cuantas cosas que mucho Ingenieros Informáticos de mi generación (y ojo que yo no lo soy) no tienen nada claro, como por ejemplo que la memoria de video está mapeada en la memoria principal y que las modificaciones de esa zona de memoria se reflejan en pantalla o tener en cuenta que z80 es little endian y las posiciones de memoria se han de introducir correspondientemente.

En este sentido y hasta que lo memoricé (lo cual tampoco supone mucho esfuerzo), agradecía mucho tener delante un mapa de memoria del CPC que me dijera desde la posición #0000 a la #FFFF qué es lo que hay. Saber donde empieza la memoria de video y dónde está la pila (y recordar que esta crece para abajo). También saber dónde se encuentra el firmware y la posición mínima de memoria donde poder cargar un programa. Cuando descubrí que podía cambiar las posiciones de pila y video por defecto ya se me abrió el cielo. :)

Sé que los últimos párrafos están fuera del alcance del video y que quizá no sea la mejor manera de empezar y que ya esté planificado cuando introducir esos conceptos, pero para mi resultaron esenciales.

En cuanto tenga un hueco me pondré con los retos.

Un saludo.

**Comment by lronaldo** [comment]
Muchas gracias por los comentarios, chicos. Son y serán de mucha utilidad :grinning:.

La intención es que el curso tenga la máxima calidad posible, por lo que tendré en cuenta vuestras opiniones y procuraré siempre que sea necesario rehacer vídeos con tal de que las explicaciones y propuestas queden bien. 

En cuanto a lo que comentáis, os digo:
- @dfreniche, tienes razón con lo del audio. Ya lo había pensado antes de subirlo, porque a mi tampoco me gusta el eco con el que suena. He intentado filtrarlo, pero no he consegido dejarlo bien. Si alguien sabe, que me aconseje. No sé si con el micro se apañará, pero sí que quiero comprarme uno bueno.
- @dfreniche, ¿Por qué me comentas lo del hexadecimal? ¿Has visto algún error en algo que digo en el vídeo? La explicación de sistemas numéricos va aparte, en otro vídeo que aún tengo que hacer :grinning: .
- @dfreniche, Sí, lo de la estética ha quedado un poco recargado. Acepto diseños y sugerencias :grinning: . ¿Alguien se anima?
- @dfreniche la hoja de cálculo está muy bien. Si la pulses un poquito y la dejas usable por "público general" podemos enlazarla en el curso para quien quiera usarla.
- @AmstradGamer, entiendo lo que dices de que hay un "gap" enorme. Lo hay. Esto es a propósito. El planteamiendo del curso es práctica primero, teoría después. La idea es que los retos, y el interés por llevarlos a cabo, genere motivación. La teoría para rellenar el gap estará disponible en otros vídeos, de modo que el estudiante motivado por realizar una tarea pueda ver las explicaciones que necesite. Siempre se van a plantear los retos antes que las explicaciones, por lo que siempre habrá gap para quien desconozca (gap que existe igualmente, quien desconoce necesita aprender), pero no habrá necesidad de verse la teoría para quien no quiera. Es, por así decirlo, "conocimiento bajo demanda". Quiero que siempre que el alumno vea un vídeo es porque quiere verlo, y no porque tiene que hacerlo. Todo esto se explicará en los vídeos introductorios del curso.
- @AmstradGamer hexadecimal, mapeo de memoria, little endian y algunas cosas más están planeadas para vídeos de teoría "on-demand". Aquí está la [lista de lo planificado para el Desafío 1-1](https://github.com/AssemblerClub/z80asmmooc/blob/master/examples/1.01-basicpixels.mc) (al final). Eso sí, cualquier cosa que se me escape y penséis que haga falta, me parece importantísimo.
- @AmstradGamer por ejemplo, la idea de visualizar el mapa de memoria me parece muy importante y tomo nota. En algún punto del Nivel 1 habrá que enseñarlo, como mínimo :grinning: . Pila y firmware también, pero para niveles posteriores. 

Conforme os pongáis con los retos, cualquier conocimiento que echéis en falta también me es importante saberlo. De igual forma, las cosas que más os cuesten, detalles que os frustren, cosas que os gusten... todo eso es esencial para potenciarlo cara a los alumnos :grinning:.

Muchísimas gracias por vuestros comentarios y ayuda. Con revisiones así seguro que podemos sacar un curso genial para mucha gente. (Nota: en la encuesta que hice en twitter, 75% (158) se muestran a favor de un curso de código máquina, 38% (80) con intención de empezar ya mismo).

**Comment by BeatrizSabater** [comment]
Buenas lronaldo.

El contenido del curso está muy bien y me gusta la forma en la que lo estás explicando (mi opinión es de una persona que no tiene gran conocimiento sobre el tema). Lo único que hecho en falta es una explicación inicial de todo, un vídeo de introducción en vez de ir explicándolo sobre la marcha.

Para mi gusto ese vídeo tendría que tener estos apartados:
- Presentación del profesor y explicación general del curso y su estructura.
- Distribución de pantalla de los vídeos, ya que al principio es un poco confuso. En la que se explicaría en cada sección qué va, por ejemplo: arriba a la izquierda podremos ver al profesor, debajo suya pondré información adicional como el estado de las direcciones de memoria, a la derecha la pantalla principal, etc.
- Herramientas que se utilizarán y dónde descargarlas.

Del sonido sólo he de decir que en este vídeo se escucha muy bien, pero que en los siguientes pierde calidad. Aunque parezca una chorrada, si tienes un micrófono del Guitar Hero te recomiendo que lo pruebes a ver qué tal suena, tiene buena calidad y yo lo uso para grabaciones y suelen quedar muy bien.

Respecto al diseño le echaré un vistazo, creo que uno de los problemas principales es el color, hace que te distraigas un poco y hace una separación rara entre las distintas partes del vídeo.

Pienso que la duración es ideal. Y creo que no me dejo nada más.

¡Un saludo! :)

**Comment by lronaldo** [comment]
Muchas gracias por tu comentario, @NatsuGirl :smile: 

En efecto, hacen falta vídeos de presentación e introducción tanto al curso y la metodología como a los niveles individualmente. Estos vídeos están planificados, pero serán los últimos en hacerse. La introducción es mejor hacerla cuando todo el contenido ya está claro y desarrollado, porque el contenido podría cambiar. Así la introducción será siempre coherente con el contenido, al ser hecha al final :).

Tengo pensado conseguir un buen micro para los próximos vídeos que grabe. De hecho, quizá rehaga los primeros vídeos con el nuevo micro. De momento no lo tengo, pero espero conseguirlo pronto. También creo que es importante :).

Cualquier sugerencia de diseño que pueda ser llevada a la práctica y mejore lo actual se agradece sin dudas :+1: 

Lo principal que más me preocupa es que probéis con los retos y me digáis dificultad, tiempo que os lleva hacerlos, complicaciones que encontráis, si son entretenidos o no... Esa es la parte esencial del curso :wink: 

Mil gracias, como siempre :grinning:

**Comment by DSkywalk** [comment]
Quizá este video desde la visión del programador lo he visto más flojo. 

Supongo que intenta introducir al debugger de Winape, pero creo que sería mejor tener "algo" que compilara y lo vieras luego en el CPC ejecutándose (incluso luego accediendo al editor y/o hacer una ejecución paso a paso). No veo muy práctico, editar memoria a pelo desde el inicio... :disappointed: 

Espero igualmente haber sido de ayuda!

**Comment by lronaldo** [comment]
@DSkywalk Sí, como te he comentado por chat, el fundamento es empezar por el bajo nivel conociendo los detalles. Por eso el módulo 1 del curso será sólo de código máquina, introduciendo algo de ensamblador, pero sólo como forma de entender el código máquina más fácilmente. 

Después, en el módulo 2 se usará el editor integrado de WinAPE para ver cómo el código se ensambla y va a parar a la RAM. Así el usuario entiende el proceso y valora la mejora de usar ensamblador respecto a código máquina, pero sin perder de vista que lo que se ejecuta es el código máquina. Eso es muy importante para luego poder perder el miedo a analizar binarios o realizar ciertos tipos de optimizaciones, además de para entender todo de forma correcta, sin imaginarse cosas que no son.

Por último, y esto no tengo claro aún si será en módulo 3 o más adelante, usaremos un editor común y corriente y un ensamblador para generar el binario. Al final terminaremos usando CPCtelera, y el estudiante entenderá todo el proceso que se realiza cuando pones make. Además, esto resta misticismo y permite valorar mejor el ensamblador como herramienta. Hay muchas concepciones equivocadas que provienen del hecho de no enseñar estos detalles, y la idea de explicarlos es evitarlas y permitir la construcción sólida de conocimiento tanto en nuevos programadores como en experimentados que quieren mejorar.

Por supuesto, aunque mi idea es seguir este hilo, pueden haber infinitas formas de conseguir lo mismo, y seguro que muchas mejores. Toda idea es siempre bienvenida. Mil gracias :smile:
