### ISSUE TITLE
Evaluación vídeo: Explicación Retos Básicos Desafío 1-1

### ISSUE THREAD

**Issue by lronaldo** [AssemblerClub/z80asmmooc#4]
Continuando con la serie del primer desafío, aquí va el [**vídeo de explicación de los retos básicos del Desafío 1.1**](https://www.youtube.com/watch?v=EHvjiJCD0_g). 

Al igual que con el anterior, os agradezco enormemente el feedback cuando tengáis tiempo para verlo.

Este vídeo está grabado con un micro direccional, aunque he tenido que postprocesar el audio porque capta ruido de fondo. También he probado a bajar un poco la música de fondo. 

En el vídeo menciono otros vídeos que aún están por hacer, pero que iré haciendo. Muy importante que me indiquéis cualquier conocimiento adicional que pueda hacer falta y que merezca la pena añadir como explicaciones de teoría opcionales (siempre a elegir por el alumno).

Mil gracias por vuestra ayuda :)

@ronsonmaria @Darky-Lucera @Davitsu @dfreniche @aalmiramolla @AmstradGamer @AugustoRuiz @Blitzman @fmgb @Raymost @villagra-abp @eduardobs79 @heclinares @peterAmoros @realmml

**Comment by ghost** [comment]
Hola.

Este video es precisamente el que echaba de menos antes de plantear los retos. Cubre el gap, o casi, solo ha faltado enseñar que el programa se puede introducir en ensamblador y obtener luego el código máquina. De hecho igual es buena idea introducir el código en ensamblador esta vez y obtener el código máquina, en lugar de introducir de nuevo el código máquina directamente. Creo que con eso se cubriría completamente el famoso gap.

Entiendo que en el video relacionado de memoria de video explicarás también los modos de video, pero echo en falta que no hayas comentado en ningún momento, o se me ha pasado, que estamos en modo 1 durante el video.

Solo eso, lo demás perfecto.

Ya se ve la cantidad de trabajo que te estás echando encima haciendo los videos tan  a la carta, como consumidor del curso, te doy por adelantado las gracias.

Un saludo.

**Comment by lronaldo** [comment]
Gracias, @AmstradGamer :smile: . Veo que cuesta bastante acostumbrarse a la idea del curso: llevamos demasiados años acostumbrados a que debemos saber las cosas para poder ponernos a hacerlas :grinning: . El planteamiento en todos los niveles será siempre a través de los retos, asumiendo que la mayoría de alumnos no sabrán cómo se hacen. La teoría estará siempre aparte para que la vean quienes la necesiten, quienes tengan curiosidad o quienes simplemente quieren saber cómo se hacen los retos. 

El Nivel 1 al completo está planteado para ser en código máquina. De hecho, el objetivo del nivel es dibujar un sprite en pantalla en código máquina. El ensamblador entrará en el Nivel 2. La idea es que los alumnos consigan hacer cosas sencillas en código máquina y entiendan como funciona. Esto permitirá que el ensamblador se perciba como un paso adelante, y mejorar la percepción y valoración de disponer de un ensamblador. Conocer los rudimentos y haberlos manejado siempre permite valorar mejor las herramientas. Además, espero que este paseo por el código máquina mejore el conocimiento y baje la percepción de "dificultad".

No he mencionado el modo 1, pero tampoco tenía pensado hacerlo. De hecho, en la explicación de la memoria de vídeo tengo pensado dividirlo en varios trozos, porque hay demasiadas cosas que explicar. Tampoco sé si explicar los modos todavía. No hay problema en que el alumno no lo sepa por ahora. El alumno va entendiendo cosas poco a poco, y luego se puede construir sobre lo entendido. De hecho, a mi me preocupa más la falta de claridad para principiantes en el ciclo de ejecución de las instrucciones, lo que son las instrucciones en sí mismo, dónde está la memoria, etc. Hay muchas cosas que cuesta percibir como alguien que desconoce.

También me preocupa que los vídeos me están quedando muy largos y que creo que no consigo condensar bien las explicaciones. En un vídeo no es tan importante dar vueltas a las cosas: la persona puede repasarlas cuantas veces quiera. El objetivo es llevar los vídeos a los 5 minutos por vídeo. A ver si lo consigo.

En cualquier caso, prefiero que sigáis apuntando todos los detalles que consideréis importantes, gap o similares. Sea como sea la planificación final, quiero tenerlo todo en cuenta. 

Mil gracias :smile:

**Comment by ghost** [comment]
A mi los videos no se me hacen largos ni me parece que te repitas en ellos. Entiendo tus argumentos para intentar reducirlo a 5 minutos.

Intento abrir mi mente a tu método, jajaja No te voy a discutir métodos didácticos a ti. :)

Como dices, te seguiré comentando lo que vaya viendo, aunque intentaré no repetirme.

Me quedo a la expectativa del siguiente.

**Comment by dfreniche** [comment]
- Coincido en que, de largos, nada. 1h de video es, quizás, excesivo. Pero obsesionarse con videos de 5min tampoco creo que sea productivo. Es mejor dividir las explicaciones como estás haciendo (modos de vídeo, qué es hexadecimal, etc.) y te saldrán de menos de 20 min, que es muy asequible. 
- como soy un inútil, hacerme recordar que MODE 1 es como CGA y sólo tienes 4 colores (nada de RGBA), y que en un byte se puede empaquetar la información de 4 pixeles de pantalla ha causado un estallido de la cabeza. Perfectamente explicado, pero haría un video (o los podríamos hacer nosotros como apoyo) profundizando en estas cosas.
- una mejora, que podría ir en un mini-video. Como me toca las narices escribir mis programas en código de máquina y perderlos, he "descubierto" (no vale reírse que os veo) que el Emulador permite guardar un volcado de la memoria del AMSTRAD, de forma que siempre puedes cargarlo y ¡magia! recuperas tu programa de vuelta. Se podría explicar esto en 5 min (como opcional)
- estos volcados podrían servir para "corregir" los deberes. Incluso podrías dar las "soluciones" con los volcados mientras no tengamos assembler "de verdad" :-D
- Quiero el tercero

**Comment by dfreniche** [comment]
Sobre sonido / diseño:
- El primero me resultó mas _bizarre_. Ahora me he acostumbrado y no lo veo tan recargado. Supongo que me impactó la estética, pero lo retro es lo que tiene.
- El sonido cumple de sobras. No nos detengamos por eso. Para mi está OK

**Comment by lronaldo** [comment]
Muchas gracias por tus comentarios, @dfreniche.

Personalmente, sigo pensando que los vídeos son largos, aunque me alegra ver que no se os hacen largos. Lo pienso porque no todo el mundo tendrá la misma motivación inicial, y los vídeos cortos ayudan a construir más motivación.

Habrá un vídeo específico sobre memoria de vídeo, su funcionamiento y codificación. De hecho, es posible que haya más de uno, porque hay mucho que ver :smile:

Si tenéis idea de hacer vosotros mismos un vídeo de apoyo, material, o lo que se os ocurra: mucho más que bienvenido :smile:. Toda contribución es siempre magnífica. Cuanto más material haya, mejor para los alumnos. Si os apetece elaborar algo, adelante, y luego ya nos preocuparemos de cómo incluirlo lo mejor posible :smile: 

Me gusta la idea de los volcados de memoria. Es una idea que fácilmente podéis elaborar en un vídeo como colaboración. El hecho de que hayan colaboraciones seguro que anima mucho más a los alumnos :). Si quieres puedes ponerte con ello y si no lo apunto en la lista, porque me parece buena idea :).

Al tema de corregir los deberes le he dado muchas vueltas. La idea de los retos es que se planteen abiertos y que no haya una solución concreta. Técnicamente, se puede programar como se quiera, y no hay una solución única. Además, algunos están planteados creativamente: para que el alumno pruebe, experimente y disfrute, sin la presión de que esté bien o mal. Seguiré pensando en ello, pero la idea principal sigue siendo que los retos sean lo más abiertos posible.

Seguimos en ello... :smile:

**Comment by magarciaguerra** [comment]
Hola a todos:

He visto los dos primeros vídeos. Me han gustado muchísimo. Interesantísimo saber por fin cómo funciona el ordenador por dentro y muy revelador saber para qué valen algunos de los numerajos que siempre vi sin comprenderlos. 

Debido a que no sé cómo funciona el hexadecimal ni cómo se convierte de binario a hexadecimal, he tenido que estar utilizando un conversor que encontré por ahí, y esto es una mejora que haría que introducir. En el vídeo se dice que hay otros vídeos que completan la información de cómo funciona el vídeo en el ordenador y que es necesario para terminar de entenderlo todo, pero no está el enlace a ese vídeo por ninguna parte. Asímismo, tampoco he visto el enlace al vídeo (al que también se hae referencia) en el que se explica el binario y el hexadecimal. Sería muy bueno poder acceder a ellos fácilmente pues, lo que me ha sido más complicado es entender cómo poner el pixel de un color determinado y ubicarlo en una de las cuatro posiciones. En mi caso, al menos, ha habido un montón de pruebas prácticamente a ciegas pues no terminé de entender cómo funciona la posición y el color. Siempre pensé que el color iba por un lado y la instrucción de la posición por otro, pero no... curiosamente todo va en la misma tirada de 8. Esta parte no me ha quedado tan clara :(

También, cada vídeo debería tener una referencia al documento que hay en la otra sección donde están los desafíos. No sé, todo está muy bien pero falta darle forma, que todo esté accesible que sea fácil ir de un lugar a otro. (Aunque está la información a la que se refiere el vídeo en la descripción de vídeo, echo de menos enlaces).

Coincido, por otra parte, con @DSkywalk en que la pantalla debería estar algo más limpia, pero tampoco es algo que estorbe demasiado.

Y, por último, qué te voy a contar que no sepas... Continuamente me asaltan dudas de si esto valdrá para el Spectrum. Quiero decir, el color 3 (azul) es el mismo azul (color 3) en el Spectrum. ¿Cuántas diferencias hay entre uno y otro? Ya has comentado que eso aparecerá más tarde, en un futuro víeo, pero mi cabeza, no deja de darle vueltas. Esto ya, como ves, es una cosa mía, no tanto de la calidad de los videotutoriales, que es altísima. Para mí, Amstrad siempre ha sido una plataforma con la que no he tenido contacto. Me crié con un zx en las manos y todos mis amigos tenían Spectrum... De hecho (y lo siento por lo pesado) para lo que quiero aprender todo esto es para hacer un port del juego actual con el que estamos trabajando ahora.

Para terminar quiero agradecerte el esfuerzo, has logrado que me entusiasme con todo lo que has contado, como bien dices, deja de haber magia para haber rigor, la curiosidad queda satisfecha y ahora comprendo muy bien cómo funcionan los procesos de un ordenador. Estoy entusiasmado y con hambre de más vídeos, con ganas de seguir tu curso. 

Muchas gracias y enhorabuena :)

**Comment by lronaldo** [comment]
Muchísimas gracias por todos tus comentarios, @magarciaguerra. Sin duda serán de utilidad :).

Siento que hayas echado en falta el vídeo de sistemas de numeración. El vídeo está planeado hacerse (de ahí que lo mencione), pero aún no está hecho. Para cuando salga el módulo completo el vídeo estará :).

Lo que comentas de que no has entendido bien la posición y el color de los píxeles es normal si no has trabajado nunca en binario. De todas formas, me interesa mucho esa parte. **Si puedes comentarme qué es lo que entendías en primera instancia, cuáles fueron tus pruebas y cómo dedujiste el funcionamiento exacto**, esa es la parte que más ayudaría a mejorar el vídeo. La intención es explicar cómo funciona pero no darlo 100% mascado. Tiene que haber una parte de investigación para el estudiante, ya que entiendo que aprender por investigación es necesario y debemos fomentarlo. Aún así, graduar bien la relación explicación/investigación es complicado. Por eso tu experiencia es muy valiosa. Si puedes detallarla, sería genial.

Respecto a Spectrum, te matizo: si pones el código máquina que se trabaja en estos vídeos en un Spectrum, hará exactamente lo mismo: copiará un valor al registro A, y de ahí a la posición C000h. Después, quedará en un bucle infinito. Desde el punto de vista del procesador, hace exactamente lo mismo. Sin embargo, el Spectrum es otro sistema, y las demás cosas no funcionan igual. Por ejemplo, la memoria de vídeo no está en C000, ni tiene el formato que has visto en Amstrad. En Amstrad hay un chip llamado CRTC que lee constantemente de la memoria y pasa estos datos al monitor, interpretando las direcciones y formato que hemos explicado. En Spectrum esto lo hace otro chip distinto, conocido por todos como la ULA, y busca los datos en otras direcciones distintas y en otro formato. De hecho, la memoria de vídeo en ZX Spectrum 48K va desde 4000h hasta 5AFFh. Si ponemos ahí nuestro programa, como estamos haciendo en Amstrad, en pantalla aparecerán píxeles en la primera fila, ya que los bytes de nuestro código máquina serán interpretados por la ULA como datos y enviados al monitor. 

Así, las diferencias entre las máquinas no están en las instrucciones del procesador o en el código máquina, que son las mismas, sino en el funcionamiento de los demás elementos de la máquina. Por eso, para poder tratarlas en el curso, tengo que hacerlas en vídeos y líneas aparte. Lo mismo para ZX Spectrum que para MSX o para Enterprise 128. Sin duda, quiero que toda esta información esté para quienes os interesa, pero tengo que estructurarla bien para que no afecte al hilo de trabajo y aprendizaje. Lo bueno es que somos muchos en el grupo y seguro que habrá gente dispuesta a colaborar para enriquecer el curso y hacer que todas estas partes estén a la altura que se espera :).

Respecto a la estética, si alguien se anima o me conseguís un diseñador que pueda mejorarla, estaré más que encantado. Puedo hacer mejoras por mi mismo, pero no van a estar a la altura, ni de lejos, de alguien que verdaderamente sepa diseñar bien.

Muchísimas gracias por los comentarios, el apoyo y la ayuda :).

**Comment by rafa32gr** [comment]
Claro, yo vengo de nuevas y no se hasta que punto se conoce el funcionamiento de ensamblador el target del video, en principio, a mi me explicaron en la carrera, que los parentesis indicaban que no se hacia referencia a esa cifra, sino al contenido de la direccion de memoria a la que aludia esa cifra, si me hago de nuevas, y pienso que no se nada de ensamblador, igual esa parte me queda un poco difusa y no muy clara.
Con respecto a la dinamica del reto, voy a intentar dejar de lado mis vicios de programacion y hacer como que toda la informacion que necesito esta dada en el video o las referencias que das,
Ya te contare.

**Comment by lronaldo** [comment]
Hola @rafa32gr ,

   Gracias por tu comentario. Creo que me acabo de dar cuenta de que los que habéis entrado recientemente no conocéis el órden en que los vídeos deberían verse y has empezado por este que es el 2º. El primero es de Desafío 1-1. Después va este, que es la explicación de los Retos Básicos del Desafío 1-1. Finalmente va el de Teoría. De hecho, la estructura del curso gira en torno a los Retos. Los vídeos de teoría son siempre opcionales. Se entiende que los desafíos son lo que motiva al estudiante y que si ya sabe hacerlos por sí solo no necesita perder el tiempo estudiando teoría que ya conoce. La teoría está disponible para apoyar a quien tiene dudas o quien necesita aprender partes que no conoce/domina para poder resolver los desafíos.

   Respecto al paréntesis, significa exactamente eso. Cuando pone "LD (#C000), A" quiere decir transferir el contenido del registro A a la posición 0xC000 de memoria (valor en A => contenido de 0xC000). ¿Puedes indicarme en qué momento del vídeo digo algo respecto a esto que confunda? Me interesa saberlo para poder mejorarlo.

   Muchas gracias por el comentario. Por cierto, los retos del vídeo están obsoletos. Estos son los [retos actualizados](https://github.com/AssemblerClub/z80asmmooc/blob/master/contents/nivel_01/retos.txt).

Un saludo.

**Comment by rafa32gr** [comment]
Pues exactamente no te sabria decir, si se que sobre la marcha, mientras veia el video, intentaba buscar cosas que pudiesen no ser exactamente como yo lo recordaba, por aquello de, "si yo no hubiese estudiado informatica, sabria hacer esto?" y en ese momento me parecio que no me quedaba claro.

Voy a ver de nuevo el video, igual si queda claro y soy yo el que no lo entendi.
Un saludo

**Comment by rafa32gr** [comment]
Dices exactamente : como C000 esta dentro de un parentesis, es una direccion de memoria, y es eso lo que yo pienso que me podia haber confundido, y por que?
C000 es una direccion de memoria si , con y sin parentesis, porque si yo pongo LD IX,&C000 pues estoy mediento una direccion de memora en el IX para por ejemplo luego ir leyendo valores que estan en esa direccion de memoria.pero si pongo LD IX,(&C000) realmente en IX no estoy metiendo &C000 sino el contenido de &C000 y en &c000 puede haber otra direccion muy distinta.

Es por eso que pienso, seguramente estoy equivocado, pero pienso que haber aclarado que los parentesis hacen que lo que se meta en A sea el contenido de, la direccion de memoria que corresponde a lo que sea que haya dentro del parentesis, bien sea el contenido de un registro, como un numero hexadecimal, hace que cuando en un código veamos paréntesis, no pensemos  mas que lo que en realidad estamos cargando es el contedido de la direccion de memoria de ese registro/valor, no ese registro/valor, porque tambien podemos poner LD A,(BC) y en principio BC es un registro, que puede tener una direccion, valores... y lo que hacemos es meter en A el contenido de la direccion de memoria correspondiente a valor que hay en BC,

Siento mucho si lio mas al personal o si me equivoco, pero es lo que pienso cuando veo el video.

**Comment by lronaldo** [comment]
No pasa nada, @rafa32gr. Aunque lo que digo en el vídeo es correcto(*), me viene muy bien saber que un comentario como ese puede haberte liado. Desde luego, nunca hubiera pensado que eso pudiera liar. Me servirá para reflexionar sobre ello y mejorar las explicaciones. Gracias 👍.

(*) Explicación de mi comentario: el paréntesis sirve para obtener contenidos de una dirección de memoria, por tanto, lo que hay dentro sabemos que es una dirección de memoria siempre. En un caso como LD IX, &C000 estamos metiendo un valor inmediato en IX. En ese momento, &C000 sólo es un valor, no una dirección de memoria. De hecho, podría ser usado como contador, o como un valor a sumar a una puntuación, o como una máscara. Ahí no podemos asegurar que &C000 sea una dirección de memoria, aunque a priori lo parezca. Sin embargo, si está entre paréntesis, no puede ser otra cosa, porque ese es el uso de los paréntesis.

**Comment by rafa32gr** [comment]
Tienes razon Fran, al final los vicios de programacion me pueden, como te dije, aprendi z80 crackeando juegos, yo veo &C000 veo la direccion de memoria, no un valor.
;-)

**Comment by rafa32gr** [comment]
Bueno, el reto 1 es muy simple, la unica dificultad puede surgir de entender como se codifican los colores en la memoria de amstrad, entendiendo eso, tan facil como convertir numeros binarios a hexadecimales.
