### ISSUE TITLE
Estética y diseño del curso

### ISSUE THREAD

**Issue by lronaldo** [AssemblerClub/z80asmmooc#6]
Miembros de @AssemblerClub/the-order-of-the-z80,
 
Hace falta vuestra ayuda. Iré al grano: 
- La estética es importantísima para un resultado profesional.
- El diseño de los vídeos actuales es insuficiente (ver [desafío 1.1](https://www.youtube.com/watch?v=Ng9n24UPJlY) | [explicación 1.1](https://www.youtube.com/watch?v=EHvjiJCD0_g) |  [teoría](https://www.youtube.com/watch?v=oc7lV3L0KL0))
  
**Objetivo:** grabar los vídeos del nivel 1 durante las próximas 5 semanas. 

**Necesario**:
- _Urgente_
  - Imagen corporativa nueva
  - Diseño de escenas para los vídeos (la distribución y el fondo)
  - Plantilla para transparencias
  - Animaciones para intro y cierre de vídeo
- _Valor añadido_
  - Animaciones explicativas de los conceptos
  - Música para intro, cierre y fondo

Cualquier ayuda que podáis aportar se aprecia enormemente. Entre todos le daremos un acabado profesional al curso. 

Contestad en este issue para que todos podamos estar informados.

Mil Gracias 😄

**Comment by Hark0** [comment]
Puedo aportar mi experiencia profesional en todo lo relativo a una "imagen corporativa" al proyecto; logotipo, tipografías, ficheros PDF. ¿Por donde empezamos? ;-)

**Comment by lronaldo** [comment]
@Hark0 Pues por donde quieras. Tienes los vídeos, sólo tienes que sugerir lo que creas conveniente. Pese a que durante 1 año la cosa ha ido poco a poco y ahora es cuando despegamos, aún estamos en el principio. Si tienes sugerencias apropiadas, es un buen momento :).

Muchas gracias 😄
