### ISSUE TITLE
Retos Nivel 1

### ISSUE THREAD

**Issue by lronaldo** [AssemblerClub/z80asmmooc#7]
Miembros de @AssemblerClub/the-order-of-the-z80,
 
Ya están listos todos los [**retos del Nivel 1 en PDF**](https://github.com/AssemblerClub/z80asmmooc/files/836832/retosNivel1.pdf)

Podéis realizar los retos en [WinAPE](http://www.winape.net), igual que en los vídeos ([desafío 1.1](https://www.youtube.com/watch?v=Ng9n24UPJlY) | [explicación 1.1](https://www.youtube.com/watch?v=EHvjiJCD0_g) |  [teoría](https://www.youtube.com/watch?v=oc7lV3L0KL0))

He preparado un [**formulario para el feedback**](https://goo.gl/forms/sopcHXXievYXC4ZG3)

**Feedback** de utilidad:
- **Tiempo** que os cuesta cada reto (podéis mediros con [Toggl](http://toggl.com/))
- **Dificultad** de cada reto
- **Problemas** que encontréis

Si tenéis preguntas o queréis compartir vuestra experiencia, comentad en este issue.

Mil Gracias 😄

**Comment by eldeljar** [comment]
Realizados los retos (salvo el último) y rellenado el formulario. El cálculo de las direcciones de memoria para posicionar un pixel me han quitado media vida. Siento no haber hecho el último reto, pero creo que hubiera estado todo el fin de semana para completarlo. 

Para personas como yo que no hemos tocado mucho ensamblador (y nada de código máquina), los retos están bastante bien para coger soltura con el depurador y las instrucciones de código máquina.

**Comment by AugustoRuiz** [comment]
Fran, esta noche te paso un análisis que hice cuando implementé la rutina
de cálculo de dirección de memoria de un pixel. Ese análisis interpreta
para que se usa cada bit de la dirección de memoria, y es bastante útil
para entenderlo...

**Comment by lronaldo** [comment]
@eldeljar Muchísimas gracias. El feedback que me das es bastante valioso. Las dificultades que te surgen sabiendo programar, pueden ser mucho más pronunciadas en novatos. 

El cálculo de las direcciones de memoria y el formato de los píxeles estarán explicado en teoría. Aún faltan los vídeos. Estoy elaborándolos justo ahora. Entiendo perfectamente que cueste, sobre todo sin apoyo. Ser capaz de hacerlo sin apoyo es un logro importante. Mucho más, si te ha costado bastante tiempo. 

Entiendo que no haber terminado los últimos retos es por una mezcla de frustración y falta de diversión. Esto es lo que más me preocupa. Ahí es donde más hay que mejorar.

@AugustoRuiz Pásamelo cuando quieras. Seguro que será útil. Gracias! 😄
