### ISSUE TITLE
Tomas de cámara

### ISSUE THREAD

**Issue by lronaldo** [AssemblerClub/z80asmmooc#8]
Miembros de @AssemblerClub/the-order-of-the-z80 ,

   Aquí os dejo 2 tomas de cámara de prueba. ¿Cuál os gusta más?
- {6 votos} [**Toma A**](https://youtu.be/HuMJtHWp6gY): Estantería lateral, fondo blanco 
- {2 votos} [**Toma B**](https://youtu.be/vWDnw7nxodE): Fondo de estanterías

   Los que estáis haciendo los [retos del nivel 1](https://github.com/AssemblerClub/z80asmmooc/issues/7), acordaos de ir poniendo el feedback. 

Gracias 👍 😄

**Comment by ronsonmaria** [comment]
Buenas noches,

A mí personalmente me gusta más la toma con el fondo blanco. La semana que
viene quiero empezar con el reto y prometo darte feedback.

Un abrazo muy grande y ánimo con el proyecto que es precioso!!

Saludos

**Comment by AugustoRuiz** [comment]
Prefiero la A, me parece más limpio. Si usas la B, tendrás que vestir de
manera que haga contraste y se te vea bien...

**Comment by eldeljar** [comment]
Entre las dos tomas, yo también prefiero la A.

**Comment by heclinares** [comment]
A mi me gusta más la B.

Quizás la A podría estar bien si se distribuyera el espacio de forma
diferente. Creo que estás demasiado escorado, es una toma para mostrar dos
elementos, sólo que el elemento de la derecha... es un armario :p

**Comment by lronaldo** [comment]
Muchas gracias por los votos y comentarios, @heclinares, @eldeljar, @ronsonmaria, @AugustoRuiz. Por el momento parece que gana la toma A, aunque la toma B también tiene sus adeptos 😄. 

Quizá opte por variar las tomas para que no sea monótono. Quizá una toma para un nivel y otra para otro podría estar bien.

**Comment by AugustoRuiz** [comment]
La toma B si vistes con más contraste no está nada mal. Lo de alternar es
buena idea.

**Comment by jmgomezpoveda** [comment]
De acuerdo con la toma A. La B parece muy busy, aunque sí podría mejorar con ropa clara y unas mechas. Sobre lo de quedar muy escorado a la banda, aplica la regla de los 2/3. También estaba pensando en lo de comentas de varias tomas, poniéndote en el "tercentil" izquierdo o derecho cada x tiempo. Pero sin cambiar demasiado, que los que somos ya mayores nos mareamos con muchos cambios :P
