### ISSUE TITLE
Vídeo 0.1:Objetivos Y Contenidos con Montaje

### ISSUE THREAD

**Issue by lronaldo** [AssemblerClub/z80asmmooc#9]
@AssemblerClub/the-order-of-the-z80 

Este es un [**vídeo introductorio con montaje completo de prueba**](https://youtu.be/lGMDyK49m8A)

[![0.1 Objetivos y Contenidos](https://img.youtube.com/vi/lGMDyK49m8A/mqdefault.jpg "0.1 Objetivos y Contenidos")](https://youtu.be/lGMDyK49m8A) 

¿Qué os parece cómo queda?

**Comment by ghost** [comment]
Solo con verlo dan ganas de ponerse a ello.

Muy bien.

**Comment by lronaldo** [comment]
@AmstradGamer Muchas gracias :+1;. Me ha costado un rato largo hacer el montaje. Para producir 2 minutos de vídeo he tardado unas cuantas horas. Espero poder automatizar cosas y hacer el trabajo más escalable. De lo contrario, tardaré milenios 😄

**Comment by DSkywalk** [comment]
Me encanta!!! :smile: 

Si sigues haciendo videos en pijama te confundiremos con el Ortiz :relaxed: 

En youtube al menos para enganchar hay que poner algún tipo de llamada cada 5/10 segundos, ese es el ritmo a la que la gente está acostumbrada.

Te dejo unos canales de divulgación con un divulgador que me encanta:
https://www.youtube.com/watch?v=yd1jx1DkXb4 (Instituto de Física Teórica IFT)
https://www.youtube.com/watch?v=Y-dMtbHQVI0 (QuantumFracture)
https://www.youtube.com/watch?v=e93XMfXVxuo (Tutoriales de Ciencia Clip, toda la serie mola y con otros divulgadores)

Espero que pueda ayudar :+1:

**Comment by DSkywalk** [comment]
Evidentemente algo así para un curso es un coñazo gordo, pero ¿quizá para presentar temas?
Saludos!!

**Comment by AugustoRuiz** [comment]
Chapeau!

**Comment by Gaspar1992** [comment]
Deberías subir el nivel de audio de los vídeos, en comparativa con otros vídeos de youtube lo escucho un poco bajo. A ver si lo tienes pronto y entramos en faena.

**Comment by lronaldo** [comment]
@Gaspar1992 El volumen lo notas bajo en este vídeo en concreto o es en todos?

¿Los demás también notáis el volumen bajo?

Esto es importante, porque precisamente he estado prestándole atención a los volúmenes y quiero estar seguro de que el volumen final es correcto.

**Comment by Gaspar1992** [comment]
En estos últimos ya que en las tomas de cámara se escucha más alto y mejor.

**Comment by dfreniche** [comment]
1. Me parece bastante bueno el video
2. Echaría en falta una musiquilla chiptune al final, de cierre :-D
3. El audio no suena todo lo bien que he visto en otros canales, pero el personal está en modo "Pro". No creo que sea lo que haga que el curso sea un éxito, sino que poco a poco y de forma sencilla se puedan ir haciendo cosas

-
Diego Freniche Brito
http://www.github.com/dfreniche/cv

**Comment by AugustoRuiz** [comment]
Para el tema del sonido, lo mejor suele ser tener un micro de corto alcance
(para evitar ruidos), y hacer un post-proceso con una compresión suave para
la voz. No normalizar, plis.

2017-04-04 7:56 GMT+02:00 Diego Freniche <notifications@github.com>:
